### ISSUE TITLE
Linux Binary is broken

### ISSUE THREAD

**Issue by Vallva** [jsreport/jsreport-dotnet-binary-linux#1]
Cannot use the Linux Binary. It fails with the error:   
   
jsreport.Local.JsReportBinaryException: Error rendering report: instance has been daemonized and initialized successfully (pid: 109)rendering has finished with errors:A critical error occurred while trying to execute the render command (2). Error while executing templating engine. Unexpected token 'return' (1). caused by error (2):-> stackError:    at onCriticalError (/snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:302:19)    at /snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:256:14    at processTicksAndRejections (internal/process/task_queues.js:97:5)caused by error (1):-> stackError:    at Client.render (/snapshot/jsreport/node_modules/jsreport-client/lib/client.js)    at processTicksAndRejections (internal/process/task_queues.js:97:5)    at async startRender (/snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:319:24)    at async /snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:226:22    at async Commander.executeCommand (/snapshot/jsreport/node_modules/jsreport-cli/lib/commander.js:242:22)Remote stack: evaluate-template-engine-helpers.js:128function now() { return new Date().toLocaleDateString(); } function nowPlus20Days() { var date = new Date(); date.setDate(date.getDate() + 20); return date.toLocaleDateString(); } function total(driverNames) { var sum = 0; driverNames.forEach(function (i) { sum += i.firstName; }) return sum; } function number(vehicleNumber) { vehicleNumber = 1; vehicleNumber++; return vehicleNumber; }
   
   
It looks like the Zip File: jsReports.zip is also unable to be opened. Might be related, maybe not. The same code works flawlessly with the Windows Binary.

**Comment by pofider** [comment]
The error mentions problems with evaluating your template.helpers

You seem to send your helpers on one line
```
function now() { return new Date().toLocaleDateString(); } function nowPlus20Days() { var date = new Date(); date.setDate(date.getDate() + 20); return date.toLocaleDateString(); } function total(driverNames) { var sum = 0; driverNames.forEach(function (i) { sum += i.firstName; }) return sum; } function number(vehicleNumber) { vehicleNumber = 1; vehicleNumber++; return vehicleNumber; }
```

This is invalid js because of the following part
```
driverNames.forEach(function (i) { sum += i.firstName; }) return sum;
```
This properly throws error `Unexpected token 'return'`.

To fix this you can simply add semicolon before return.
```
driverNames.forEach(function (i) { sum += i.firstName; }); return sum;
```
